### ISSUE TITLE
Lua 5.2 Gotos

### ISSUE THREAD

**Issue by steamp0rt** [SquidDev/Cobalt#26]
http://lua-users.org/wiki/GotoStatement

Would be useful.

**Comment by steamp0rt** [comment]
Why was this marked as `wontfix`?

**Comment by SquidDev** [comment]
Cobalt is a Lua 5.1 implementation, and thus will not implement any major 5.2 feature.

**Comment by steamp0rt** [comment]
Huh, I thought it was kind of a weird 5.1-5.2 hybrid
