### ISSUE TITLE
Difference with LUAJ

### ISSUE THREAD

**Issue by NickKemp** [SquidDev/Cobalt#39]
I am trying to test Cobalt out and currently have the following that works with LUAJ where I call an Init Function and then call another function to get the result. I cannot see how this is implemented in Cobalt. 

	public static void main(String[] args) throws Exception 
	{
		String script = "add2nums.lua";
		
		// create an environment to run in
		Globals globals = JsePlatform.standardGlobals();
		globals.get("dofile").call( LuaValue.valueOf(script));
				
      //call the function InitAdd2Nums with two parameters 5, and 5
		LuaValue InitAdd2Nums = globals.get("InitAdd2Nums");
		LuaValue retvalsInit = InitAdd2Nums.call(LuaValue.valueOf(5), LuaValue.valueOf(4));	
		
		//print out the result from the lua functio
		System.out.println(retvalsInit.tojstring(1));
		
      //call the function Add2Nums with no parameters and get result back
		LuaValue Add2Nums = globals.get("Add2Nums");
		LuaValue retvalsAdd = Add2Nums.call();			

		//print out the result from the lua functio
		System.out.println(retvalsAdd.tojstring(1));
	}

local num1
local num2
local num3

function InitAdd2Nums( pnum1, pnum2 )
    num1 = pnum1
    num2 = pnum2
    print ("INIT num1 " .. num1)
    print ("INIT num2 " .. num2)
    return 0
end

function Add2Nums()
    print ("ADD num1 " .. num1)
    num1 = num1 * 10
    print ("ADD num2 " .. num2)
    num3 = num1 + num2
    num4 = num3 / num2
	return num3
end

**Comment by SquidDev** [comment]
Off the top of my head, it should look something like this:

```java
LuaState builder = LuaState.builder().build();
LuaTable globals = JsePlatform.debugGlobals(state);
globals.rawget("dofile").call(state, ValueFactory.valueOf(script));

LuaValue InitAdd2Nums = globals.rawget("InitAdd2Nums");
LuaValue retvalsInit = InitAdd2Nums.call(state, ValueFactory.valueOf(5), ValueFactory.valueOf(4));

// etc...
```

Basically the main difference is that you need to explicitly pass the `LuaState` around.
