### ISSUE TITLE
hey i need help learning this api 

### ISSUE THREAD

**Issue by lolBoi9696** [SquidDev/Cobalt#49]
so i need to learn how to use this api can you tell me how to load a lua file and read and write stuff to it be awesome just need to use this for a project i want to like call functions in java using lua from this api but i cant figure out how to use this i appreciate if you helped me i really need this.

**Comment by SquidDev** [comment]
I'd personally not _really_ recommend using Cobalt for your own project. It's very much written for my specific use case  (i.e. a fantasy computer), which means there's probably some design choices which aren't suitable for everything, as well as being pretty poorly documented.

That said, if you still want to go ahead I'll cover the basics. The original question was pretty open ended, so do comment if you want something more specific:

## Depending on Cobalt
Cobalt is hosted on my maven (`https://squiddev.cc/maven/`), with the identifier `'org.squiddev:Cobalt:0.5.1-SNAPSHOT'`. Not sure what build system you're using, but on Gradle you can depend on it using:

```groovy
repositories {
  maven { url 'https://squiddev.cc/maven/' }
}

dependencies { implementation 'org.squiddev:Cobalt:0.5.1-SNAPSHOT' }
```

## Using Cobalt
The best reference here is probably [the test directory](https://github.com/SquidDev/Cobalt/tree/master/src/test/java/org/squiddev/cobalt) - I'm afraid I haven't updated the examples in quite some years now.

A basic example would look something like this though:

```java
LuaState state = new LuaState(); // Create Lua VM
LuaTable globals = JsePlatform.debugGlobals(state); // Create a table

// Load a function from a file
LuaFunction program;
try(FileInputStream file = new FileInputStream("file_to_load.lua")) {
  // Alternatively use a ByteArrayInputStream or something to load from a string.
  program = LoadState.load(state, file, "@file_to_load.lua", globals);
}

LuaThread.runMain(state, program); // Actually run the program.
```

**Comment by lolBoi9696** [comment]
if i built it as cobolt as a jar will it still work??

**Comment by SquidDev** [comment]
Yes.

**Comment by lolBoi9696** [comment]
quick question would this work?
```public void loadLua(String path) throws LuaError, InterruptedException, IOException, CompileException {
		LuaState state = new LuaState(); // Create Lua VM
		LuaTable globals = JsePlatform.debugGlobals(state); // Create a table

		// Load a function from a file
		LuaFunction program;
		try(FileInputStream file = new FileInputStream(path + ".lua")) {
		  // Alternatively use a ByteArrayInputStream or something to load from a string.
		  program = LoadState.load(state, file, "@" + path + ".lua", globals);
		  file.close();
		}

		LuaThread.runMain(state, program); // Actually run the program.
	}```

**Comment by SquidDev** [comment]
I put 15-20 minutes into writing the top comment. I'm sure you can spend 30 seconds trying and seeing for yourself.

Merry Christmas!
