### ISSUE TITLE
How to set memory limit?

### ISSUE THREAD

**Issue by DariusSG** [SquidDev/Cobalt#55]

**Comment by SquidDev** [comment]
I'm afraid you can't on a per-VM level. We just use the Java memory allocator and GC, which limits what controls you have.

It's obviously possible to control how much memory the whole JVM uses, but that's probably not what you want.

**Comment by DariusSG** [comment]
OK then how about implementing a memory limit on a VM level and how hard would it be?

**Comment by SquidDev** [comment]
Well, you'd have to implement your own allocator and GC, so it's pretty complex. If you really need this, there's a couple of alternative solutions:
 - JNLua: This binds to the native Lua libraries. You can provide a custom allocator which limits the amount of memory (for example, [MightyPirate's fork of JNLua does this][oc]).
 - [waluaigi]: This compiles to wasm, which allows you to limit the memory by default. However, it is incredibly slow (about 100x worse than PUC Lua).

[oc]: https://github.com/MightyPirates/OC-JNLua/blob/eris/jnlua/src/main/c/jnlua.c#L211-L248
[waluaigi]: https://github.com/SquidDev/waluaigi

**Comment by DariusSG** [comment]
Will this ever get a memory limit?

**Comment by SquidDev** [comment]
No, afraid not.

**Comment by DariusSG** [comment]
Is there any good documentation for JNLua or forks that exposes Lua objects in Java, like a your LuaTable, LuaString, etc.

**Comment by SquidDev** [comment]
JNLua has a [`DefaultConverter`](https://github.com/MightyPirates/OC-JNLua/blob/master/src/main/java/li/cil/repack/com/naef/jnlua/DefaultConverter.java) which sort of wraps things like Cobalt does.

> Note, trying to add memory limit to CC: restitched without having to rewrite a lot of the Lua related code

I'm afraid whatever route you go is going to need a new implementation of `ILuaMachine`, which is quite a lot of code. [You can see what I did for waluaigi](https://github.com/SquidDev-CC/CC-Tweaked/commit/7e74725de7e2395adc7794d754e3adbd9d7d1b16), if that's helpful.

**Comment by DariusSG** [comment]
In JNLua, How do I get the thread index because newthread() is a void function? or should I ask this on StackOverflow?
