### ISSUE TITLE
`;` rules not consistent with PUC Lua

### ISSUE THREAD

**Issue by Lupus590** [SquidDev/Cobalt#60]
Discovered on discord with the CC FAQ bot.

![image](https://user-images.githubusercontent.com/9790321/154571118-a8b7a212-2b35-4be2-98b2-63ea4a6a687e.png)
![image](https://user-images.githubusercontent.com/9790321/154571032-5aea7cfc-e9bb-43e6-a885-79817e409aaf.png)

**Comment by Lupus590** [comment]
Never mind, Alex is using 5.2+ and just 5.1 reacts like this.

**Comment by Lupus590** [comment]
Not a bad thing to check for in #50 though

**Comment by MCJack123** [comment]
https://github.com/SquidDev/Cobalt/blob/b9a8435a1caf4fafd49382f51cdd389838b01b39/src/main/java/org/squiddev/cobalt/compiler/LexState.java#L2133-L2136

Already way ahead of you.
