### ISSUE TITLE
is there an interpreter?

### ISSUE THREAD

**Issue by bentxt** [SquidDev/Cobalt#72]
Hi,
Is it possible to use Cobalt with cli?

**Comment by SquidDev** [comment]
No. Cobalt is mostly intended to be used as a library.

**Comment by bentxt** [comment]
Would you mind pointing to an example or the appropriate location where I can learn on how to include Cobalt?

**Comment by Lupus590** [comment]
Cobalt is very much designed for [CC:Tweaked](https://github.com/cc-tweaked/CC-Tweaked), so the best example is probably that.
