### ISSUE TITLE
Does have a  plane to support "goto" keyword ?

### ISSUE THREAD

**Issue by lingbl** [SquidDev/Cobalt#74]
Does have a  plane to support "goto" keyword ?  I want to use lua5.2 , lua5.1 is too old.

**Comment by SquidDev** [comment]
Eventually _yes_. I want to update Cobalt to target Lua 5.2/5.3, but it's not very high on the priority list

**Comment by SquidDev** [comment]
If you want to run Lua in Java, LuaJ _does_ support Lua 5.2 - https://github.com/luaj/luaj/.
