### ISSUE TITLE
Missing punctuation in pattern match MASK_PUNCT 

### ISSUE THREAD

**Issue by MaxThlon** [SquidDev/Cobalt#75]
Hello, i'm using metalua for generating ast from lua source and the pattern for MASK_PUNCT inside StringMatch.java is missing punctuations values.
I've check inside luaj current source code and the test i've found is this one

if ( ( c >= '!' && c <= '/' ) || ( c >= ':' && c <= '@' ) || ( c >= '[' && c <= '`' ) || ( c >= '{' && c <= '~' ) ) {
  CHAR_TABLE[i] |= MASK_PUNCT;
}
https://github.com/luaj/luaj/blob/master/src/core/org/luaj/vm2/lib/StringLib.java at line 834

Meaning it's an correction made by luaj your missing inside
https://github.com/SquidDev/Cobalt/blob/master/src/main/java/org/squiddev/cobalt/lib/StringMatch.java at line 39

Thanks in advance for the correction, otherwise tell me if you prefer a merge request from me...

For more explanations of how i'm trying to make metalua woking, i'm using checks.lua from https://github.com/denglf/FormatLua and last metalua from luarocks, to prevent using dll ...

**Comment by SquidDev** [comment]
Thank you for the report!
